[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "always"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
